server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://39.100.99.143:3306/train?useUnicode=true&characterEncoding=utf-8
    username: root
    password: yurui1993
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configLocation: classpath*:/SqlMapConfig.xml

logging:
  level:
    com.example.trainline.mapper: debug
